### PR TITLE
SISRP-38681 - Show Committee Card in Adviser Dashboard - UX Development

### PR DESCRIPTION
**Pull request by davidlimcheng**
https://jira.berkeley.edu/browse/SISRP-38681

* Brings Committees to Advisors
* Reorders some stuff that wasn't alphabetical
* User Overview, like so many other things, is in dire need of a refactor

### CODE REVIEW

**Comment by lyttam** [comment]
@davidlimcheng Thanks for alphabetizing stuff and refactoring the front-end committees code.

One thing I notice is it looks like the studentOverviewController is looking for both student and faculty committees. Was there any discussion of whether an advisor should see the faculty committees card? That card is meant to be shown to a user who is a member of a committee.

I suspect advisors should never see faculty committee data. If that's the case, the controller should get an advisor-only version of the feed that only contains the data from `MyCommittees::StudentCommittees`. We don't want to expose the faculty data to the front-end.

**Comment by davidlimcheng** [comment]
Ah, great catch @lyttam !  That makes total sense, I was in a hurry and didn't realize `Merged` had both types of data.  Seems very obvious in hindsight.  I'll amend this PR.

**Comment by davidlimcheng** [comment]
@lyttam While working on this, I saw that `MyCommittees::Merged` is cached, while `MyCommittees::StudentCommittees` is not.  So, if we switch to `StudentCommittees`, we'll have to make the decision whether to cache the `StudentCommittees` data by itself or not.

According to Google Analytics over the past month, `/user/overview/:uid` got 106,222 views (1.57% of total), while `/academics` got 2,470,145 (36.44% of total).  It might actually be worth it to pull from `Merged` as opposed to `StudentCommittees` to leverage the already-existing caching.

What do you think about removing all the Faculty data parsing in the front-end, but leaving the endpoint to pull from `Merged`?

**Comment by lyttam** [comment]
@davidlimcheng  The endpoint can pull from `Merged` but then it needs to remove the Faculty data before passing to the front-end.  Otherwise, a user can see that data in their browser console.

Or, you could cache the `Merged` feed and the `StudentCommittees` feed separately, and decide in the controller which one to call. {{MyAcademicsController}} does this.

**Comment by davidlimcheng** [comment]
@lyttam Good point.  Amended with:

1. `facultyCommittees` is parsed out in `AdvisingStudentController`
2. Renamed the URL and controller method from `committees` to `student_committees`.

Ready for re-review.

**Comment by lyttam** [comment]
Thanks!

**Pull request merged**
