### PR TITLE
Merge master branch into sis-master

### PR DESCRIPTION
**Pull request by christianv**
Fix merge conflicts & following files:

* Require lodash in index.js
* Require lodash in profileController & tasksController
* `package.json` & `gulpfile.js`

### CODE REVIEW

**Comment by christianv** [comment]
Trying to make a PR on a Sunday results in test failures (date shifting issue) so let's try to restart the Travis build tomorrow.

**Comment by raydavis** [comment]
Restarted Travis job...

**Comment by christianv** [comment]
@raydavis and travis is green :).

**Comment by raydavis** [comment]
... and @christianv is waiting. :)

**Pull request merged**
