### PR TITLE
CLC-4955 - Update E-Grade Export tool to run in CalCentral Context

### PR DESCRIPTION
**Pull request by redconfetti**
https://jira.ets.berkeley.edu/jira/browse/CLC-4955

### CODE REVIEW

**Comment by raydavis** [comment]
Loads of RSpec errors, @redconfetti , but they look all of a type.

**Comment by christianv** [comment]
@redconfetti front-end lgtm

**Comment by raydavis** [comment]
Back-end changes look good too -- just need to kick the tests back into line, and we can wrap it up.

**Comment by redconfetti** [comment]
@raydavis - It's odd that the [default setting for url_root](https://github.com/ets-berkeley-edu/calcentral/blob/0a0f65cb/config/settings.yml#L66), which isn't being overridden in the [test config](https://github.com/ets-berkeley-edu/calcentral/blob/0a0f65cb/config/settings/test.yml#L8), is 'http://localhost:12345', but instead the test is getting 'https://ucb.beta.example.com' ?!?

I guess I'll just have to mock the response from Settings.canvas_proxy for url_root in this test so that it passes in any environment.

**Comment by redconfetti** [comment]
Oh nevermind. I'm getting the same errors locally. I expected them to only happen within Travis environment.

**Pull request merged**
