### PR TITLE
SISRP-25708 - Grad Degree Progress card - Add additional links

### PR DESCRIPTION
**Pull request by redconfetti**
https://jira.berkeley.edu/browse/SISRP-25708

### CODE REVIEW

**Comment by davidlimcheng** [comment]
@redconfetti  Did you mean to link this to [SISRP-28109](https://jira.berkeley.edu/browse/SISRP-28109)?

**Comment by davidlimcheng** [comment]
@redconfetti LGTM, do you mind fixing the JIRA ticket #s before merging, just in case?

**Comment by redconfetti** [comment]
@davidlimcheng - No. I meant to link to the parent JIRA. I like sub-tasks for tracking time, but I prefer that PRs are associated with the parent JIRA. 

@nkutub @lyttam what do you think?

**Comment by lyttam** [comment]
@redconfetti if you're going to link to the parent JIRA, I would suggest also including a link to the subtask.  When I read PRs, I usually look at the JIRA first so I can understand the business/functional requirement behind what's being changed.

**Comment by lyttam** [comment]
Changes look good though.

**Comment by davidlimcheng** [comment]
@lyttam @redconfetti Yep!

**Pull request merged**
