### PR TITLE
NOJIRA, add cs_billing endpoint to verify_sis_api_endpoints script

### PR DESCRIPTION
**Pull request by johncrossman**
New endpoint: `/BILLING_API/get?EMPLID=`

`echo_usage()` moved up to serve as both function and script documentation.

### CODE REVIEW

**Comment by johncrossman** [comment]
Note: `/${CAMPUS_SOLUTIONS_ID}?id-type=uid` was deliberately removed. It is not used in our codebase.

**Comment by paulkerschen** [comment]
Thanks @johncrossman

**Comment by christianvuerings** [comment]
@davidlimcheng FYI - we might have to update this script once we have the actual URL in CS.

**Comment by christianvuerings** [comment]
@davidlimcheng FYI - we might have to update this script once we have the actual URL in CS.

**Pull request merged**
