### PR TITLE
CLC-4683 - Update gems - autoprefixer-rails / icalendar / active_attr

### PR DESCRIPTION
**Pull request by christianv**
https://jira.ets.berkeley.edu/jira/browse/CLC-4683

### CODE REVIEW

**Comment by christianv** [comment]
To make these PR's easier to review, I've included the changelog messages in the git commits:

screen shot 2015-01-07 at 12 29 40 pm

**Comment by ctweney** [comment]
The Travis test failures look like they are highly related to the google API client change.

**Comment by ctweney** [comment]
@christianv Let me know if you'd like help resolving the test failures.

**Comment by christianv** [comment]
@ctweney indeed, I've updated this PR to not include the google API client gem update. I've created https://jira.ets.berkeley.edu/jira/browse/CLC-4700 to follow up and if you want to have a look, that would be great.

**Comment by raydavis** [comment]
@christianv , the LDAP update broke the relevant testext tests on Bamboo. Can you take a look?

**Comment by christianv** [comment]
@raydavis would it be possible to point me to the build? Did some searching on bamboo but couldn't immediately find it.

Locally I was able to reproduce the failed build and it's related to https://github.com/ruby-ldap/ruby-net-ldap/issues/175

They've already fixed it in master so we'll have to wait for the next release `>0.10.1` -
https://jira.ets.berkeley.edu/jira/browse/CLC-4726

**Comment by christianv** [comment]
Removed the `net-ldap` upgrade from this PR

**Comment by christianv** [comment]
https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CLCMVPCHRISTIAN202-4 now seems to be successful - @raydavis

**Comment by ctweney** [comment]
looks good, thanks for the documentation on the problem !

**Pull request merged**
