### PR TITLE
SISRP-29183 Drop Financial Aid Transition Dates table

### PR DESCRIPTION
**Pull request by raydavis**
https://jira.berkeley.edu/browse/SISRP-29183

### CODE REVIEW

**Comment by paulkerschen** [comment]
@raydavis Did a Git quirk prevent `app/models/finaid/fin_aid_year.rb` from being removed as well?

**Comment by raydavis** [comment]
It did, @paulkerschen !

**Comment by raydavis** [comment]
PR unquirked. Meanwhile, Travis-CI appears to rely on AWS for logging I/O...

**Comment by paulkerschen** [comment]
There never were Financial Aid Transition Dates; we have always been at war.

**Pull request merged**
