### PR TITLE
CLC-6157, script to verify required SIS endpoints (e.g., used by Ops)

### PR DESCRIPTION
**Pull request by johncrossman**
https://jira.ets.berkeley.edu/jira/browse/CLC-6157

[CLC-6123](https://jira.ets.berkeley.edu/jira/browse/CLC-6123) demonstrates a need for automated verification of SIS APIs. This script will read configs from specified YAML file.

See curl conventions described in [ChrisT exit notes](https://docs.google.com/document/d/1JspjhNQ-rHL1PsnpwL3n3TUprxk55Tej2t20XLExRzI/edit#)

### CODE REVIEW

**Comment by johncrossman** [comment]
I need amend the commit. The section to verify Campus Solutions API has a crosswalk related variable. Copy and paste does it again.

**Comment by johncrossman** [comment]
Okay, fixed.

**Comment by paulkerschen** [comment]
My limited Bash-scripting knowledge discovers no problems here, but maybe @raydavis should have a look too.

**Comment by dkawase** [comment]
I confirmed the script ran without issues on QA.

**Comment by paulkerschen** [comment]
If it's good for @dkawase, it's good for me.

**Pull request merged**
