### PR TITLE
SISRP-17230 - Hook-Up Back-End to CS API Endpoint

### PR DESCRIPTION
**Pull request by davidlimcheng**
https://jira.berkeley.edu/browse/SISRP-17230

For `cs_billing`, items, including `billing_summary.html`, `billing_activity.html`, and `billing.rb`

Also replaced the `billing_details.xml` fixture with actual test data.

### CODE REVIEW

**Comment by davidlimcheng** [comment]
Created [SISRP-17257](https://jira.berkeley.edu/browse/SISRP-17257) for Rspec tests.

**Comment by davidlimcheng** [comment]
Ah, forgot to rewrite the current Rspec tests to jive with the actual fixture test data.  Will amend my commit shortly.

**Comment by davidlimcheng** [comment]
Should be good2go now.  I just realized how terrible of a PR name this is and will be more specific in the future.

I also snuck in a minor change to the front-end controller, that will default select the first `itemTerm` in the `activity` list, as opposed to defaulting to `all terms`.

**Comment by christianvuerings** [comment]
@davidlimcheng Front-end lgtm

**Pull request merged**
