### PR TITLE
SISRP-9881 Make archiveUrl feature flag default to off, and don't exp…

### PR DESCRIPTION
**Pull request by ctweney**
…lode when it's absent

https://jira.berkeley.edu/browse/SISRP-9881

### CODE REVIEW

**Comment by ctweney** [comment]
Oops, test failure -- I'll push a fix.

**Comment by ctweney** [comment]
New commit should fix T.

**Comment by christianv** [comment]
@ctweney @raydavis @johncrossman @paulkerschen could we make sure that we don't forget to enable this flag for GL3?

**Comment by johncrossman** [comment]
@christianv I'm going to create section on release-specific instructions page for v68, our subsequent release. Good place for reminder?

**Comment by christianv** [comment]
@johncrossman perfect, thanks!

**Pull request merged**
