### PR TITLE
SISRP-38270 - Fixes MyTasks::Merged spec to test against consistent with date/time

### PR DESCRIPTION
**Pull request by redconfetti**
https://jira.berkeley.edu/browse/SISRP-38270

### CODE REVIEW

**Comment by redconfetti** [comment]
I was able to resolve this issue locally, but it's still failing within TravisCI environment and I'm not sure why. I'm trying to see if I can configure Vagrant to reproduce a TravisCI environment locally. I've found the following resources helpful:

* [How to reproduce a Travis CI build environment for debugging](https://stackoverflow.com/questions/29753560/how-to-reproduce-a-travis-ci-build-environment-for-debugging)
* [How to run Travis CI Locally](https://stackoverflow.com/questions/21053657/how-to-run-travis-ci-locally)
* [Multiple Vagrant VMs](http://www.thisprogrammingthing.com/2015/multiple-vagrant-vms-in-one-vagrantfile/)
* [TravisCI Minimal Trusty64 image](https://app.vagrantup.com/travis-ci/boxes/ci-minimal-trusty64)
* [TravisCI Build](https://github.com/travis-ci/travis-build)
* [TravisCI Worker](https://github.com/travis-ci/worker)
* [CalCentral - Vagrant Readme](README-VAGRANT.md)

**Comment by paulkerschen** [comment]
A couple of notes, @redconfetti:
- We've been burned in the past by directly stubbing Time.now in specs; it caused occasional order-dependent failures in later tests. See https://github.com/ets-berkeley-edu/calcentral/pull/4331.
- One thing that can cause weird differences between local environments and Travis is system timezone. Have you tried changing the timezone on your local machine to UTC to see if that reproduces Travis behavior?

**Comment by redconfetti** [comment]
I've decided to abort this Travis setup. Here is [my configuration](https://gist.github.com/redconfetti/82e8b4f024668f3fcb541cf1c229cf78).

I'm currently getting this error. At this point I think I should go with @paulkerschen 's suggestions for exploring the failure.

```
$ git clone --depth=1 --branch='' git@github.com:redconfetti/calcentral.git redconfetti/calcentral
Cloning into 'redconfetti/calcentral'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

The command "eval git clone --depth=1 --branch='' git@github.com:redconfetti/calcentral.git redconfetti/calcentral " failed. Retrying, 2 of 3.

Cloning into 'redconfetti/calcentral'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

The command "eval git clone --depth=1 --branch='' git@github.com:redconfetti/calcentral.git redconfetti/calcentral " failed. Retrying, 3 of 3.

Cloning into 'redconfetti/calcentral'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

The command "eval git clone --depth=1 --branch='' git@github.com:redconfetti/calcentral.git redconfetti/calcentral " failed 3 times.



The command "git clone --depth=1 --branch='' git@github.com:redconfetti/calcentral.git redconfetti/calcentral" failed and exited with 128 during .

Your build has been stopped.
```

**Comment by redconfetti** [comment]
Had a talk with @paulkerschen and he clarified that the [Timeshifter](https://github.com/ets-berkeley-edu/calcentral/blob/d8118047/lib/timeshifter.rb) class exists specifically for our testing fixtures, so that we can specify dates/times in relative to when the fixtures

https://github.com/ets-berkeley-edu/calcentral/blob/9684f0bf/fixtures/xml/campus_solutions/checklist.xml#L9

I've documented this in our [Unit Testing docs](https://confluence.ets.berkeley.edu/confluence/display/MYB/Unit+Testing#UnitTesting-TimeShifter)for future reference. Thanks @paulkerschen

**Comment by davidlimcheng** [comment]
Nice, guys!

**Pull request merged**
