### PR TITLE
[QA] SISRP-22147 - 6.0 - My Campus Links - remove Change of Academic Plan link

### PR DESCRIPTION
**Pull request by dfkaye**
https://jira.berkeley.edu/browse/SISRP-22147

Master PR https://github.com/ets-berkeley-edu/calcentral/pull/5706

### CODE REVIEW

**Comment by johncrossman** [comment]
Looks right, @dfkaye  Do the release instructions need "refresh Campus Links" step?

**Comment by raydavis** [comment]
Thanks for asking @johncrossman , but the refresh-Campus-Links step is already there. We just need to add this to the list of linked JIRAs.

**Comment by johncrossman** [comment]
@dfkaye Can we just comment out the block or set all flags to false?  ... We just don't want some other dev to go chasing down the CS URL.

**Comment by raydavis** [comment]
@johncrossman , personally I'd vote for deletion. The original code and the original link are both documented in the JIRA ticket.

**Comment by johncrossman** [comment]
Thanks @raydavis  Makes sense.

**Pull request merged**
