### PR TITLE
[QA] SISRP-23528 - Cal Central Suppress zero amounts in billing details

### PR DESCRIPTION
**Pull request by redconfetti**
https://jira.berkeley.edu/browse/SISRP-23528

See DEV PR #5773

### CODE REVIEW

**Comment by redconfetti** [comment]
@davidlimcheng I created this QA PR for you, so that it's closer to being ready for merger, if you receive the greenlight from Ben Hubbard, Paul Farestveit, and Ray Davis.

**Comment by raydavis** [comment]
Looks nice and focused. +1 from me.

**Comment by davidlimcheng** [comment]
Thank you @redconfetti  and @raydavis !!

**Comment by raydavis** [comment]
I pinged @pfarestveit and Ben for objections at https://jira.berkeley.edu/browse/SISRP-23528 .

**Comment by raydavis** [comment]
@pfarestveit confirmed he'll be able to test this one.

**Pull request merged**
