### PR TITLE
SISRP-38331 - CalCentral: Hide Pathways Selection Link from GEP Waitlist

### PR DESCRIPTION
**Pull request by davidlimcheng**
https://jira.berkeley.edu/browse/SISRP-38331

"gep" stands for "Global Edge Program"

### CODE REVIEW

**Comment by davidlimcheng** [comment]
Hold off on merging this.  Might get pulled from the release.

**Comment by davidlimcheng** [comment]
Nvm we're good - merge to your heart's desire

**Comment by lyttam** [comment]
@davidlimcheng would you consider spelling out 'gep' in the code, perhaps as `global_edge_program`?  There's no harm in making longer variable names, and I think it would be clearer to me and future developers.

**Comment by davidlimcheng** [comment]
@lyttam Good call.  Will change `gep` to `is_global_edge`

**Comment by davidlimcheng** [comment]
@lyttam - Renamed all `gep` variables to something less cryptic.

**Comment by lyttam** [comment]
@davidlimcheng Awesome thanks! Looks good.

**Pull request merged**
