### PR TITLE
[QA] SISRP-26895 - AA/UX: Student Success Card (Future Term)

### PR DESCRIPTION
**Pull request by davidlimcheng**
https://jira.berkeley.edu/browse/SISRP-26895

QA PR of #6090

### CODE REVIEW

**Comment by raydavis** [comment]
@davidlimcheng , has this been (somewhat) validated on a Master-running server? That's always reassuring...

**Comment by davidlimcheng** [comment]
@raydavis, great idea - I just reached out to Liz (functional owner) to validate in cc-dev right now.  I'll update this once she gives the green light.

**Comment by raydavis** [comment]
Thanks, @davidlimcheng -- if Liz is delayed & you're able to do a quick sanity check yourself, that's good enough for me, too!

**Comment by davidlimcheng** [comment]
Looks good to me @raydavis, although I did encounter a separate bug which I've logged at https://jira.berkeley.edu/browse/SISRP-27546.  I'd like to open a separate Master/QA PR for that one, if that's OK with you - so this one should be good to go.

**Comment by raydavis** [comment]
Thanks for the update, @davidlimcheng

**Pull request merged**
