### PR TITLE
CLC-6677 Delete most non-Junction front-end files

### PR DESCRIPTION
**Pull request by raydavis**
https://jira.ets.berkeley.edu/jira/browse/CLC-6677

I only scratched the surface, but it's a pretty broad service.

### CODE REVIEW

**Comment by johncrossman** [comment]
@raydavis - deal with Travis failure now or clean up after merge?

**Comment by raydavis** [comment]
Thanks, @johncrossman . Before merging, for sure.

**Comment by raydavis** [comment]
Travis OK-ed this amended PR, @johncrossman

**Comment by paulkerschen** [comment]
O Campus! My Campus! Our fearful trip is done.

**Pull request merged**
