### PR TITLE
Merge master into sis-master

### PR DESCRIPTION
**Pull request by christianvuerings**

### CODE REVIEW

**Comment by johncrossman** [comment]
@christianvuerings @paulkerschen I think the conflict is in `activity.html`:
```
<<<<<<< HEAD
  <div data-ng-if="archiveUrl && (api.user.profile.roles.student || api.user.profile.roles.applicant)" class="cc-text-center cc-widget-padding">
    <a data-cc-campus-solutions-link-directive="archiveUrl" data-cc-outbound-enabled="false">Archive of Official Communications</a>
  </div>
=======
  <div data-ng-include="'widgets/activity_archive.html'"></div>
>>>>>>> sis-master
```
See #4625 for change on *master* as seen above. In prep for mega-merge can we cherry-pick commit 0a7dd02786a33763621473bdedea811cec6f56a2 and push to sis-master?

**Comment by paulkerschen** [comment]
@johncrossman: Open at #4632.

**Comment by paulkerschen** [comment]
@johncrossman: I was precipitate. I think that before the mega-merge, master actually needs to revert the modification to /widgets/activity.html in 0a7dd02. 

See 7ad727e, which moved part of /widgets/activity.html into the new /widgets/activity_archive.html. Presumably it should be that new file, not the old one, which gets the `api.user.profile.roles.applicant` addition.

@christianvuerings should review this.

**Comment by christianvuerings** [comment]
@paulkerschen & @johncrossman - follow up at #4633 which fixes the merge conflict

**Pull request closed without merging**
