### PR TITLE
SISRP-16714 EdoDb: create enrolled sections query

### PR DESCRIPTION
**Pull request by paulkerschen**
https://jira.berkeley.edu/browse/SISRP-16714

### CODE REVIEW

**Comment by redconfetti** [comment]
From Travis log:
```
Pending:
  CampusSolutions::Deposit SISRP-13071
    # No reason given
    # ./spec/models/campus_solutions/deposit_spec.rb:27

Finished in 3 minutes 31.7 seconds (files took 22.28 seconds to load)
2834 examples, 0 failures, 1 pending
```

**Comment by johncrossman** [comment]
@paulkerschen @raydavis Another `jscs` update in Travis land?

**Comment by paulkerschen** [comment]
It's more interesting than that, @johncrossman; I think someone unpublished a package from npm which is causing Travis-wide mayhem. From our build log:

```
-[0G\[0G[37m[40mnpm[0m [0m[30m[43mWARN[0m [0m[35mengine[0m is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.36","npm":"1.4.28"})
[0m[37m[40mnpm[0m [0m[30m[43mWARN[0m [0m[35mengine[0m is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.36","npm":"1.4.28"})
[0m-[0G-[0G\[0G[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m Error: version not found: left-pad@0.0.3
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     at /home/travis/.nvm/v0.10.36/lib/node_modules/npm/lib/cache/add-named.js:125:12
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     at saved (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:167:7)
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     at Object.oncomplete (fs.js:108:15)
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m If you need help, you may report this *entire* log,
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m including the npm and node versions, at:
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     <http://github.com/npm/npm/issues>
[0m
[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35mSystem[0m Linux 3.13.0-40-generic
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35mcommand[0m "/home/travis/.nvm/v0.10.36/bin/node" "/home/travis/.nvm/v0.10.36/bin/npm" "install"
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35mcwd[0m /home/travis/build/ets-berkeley-edu/calcentral
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35mnode -v[0m v0.10.36
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35mnpm -v[0m 1.4.28
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35mnot ok[0m code 0
[0m
```

See https://github.com/azer/left-pad/issues/4

**Comment by christianvuerings** [comment]
@redconfetti Please don't merge PRs when they have 2 failing builds on travis.
Working on a shared remote branch could be one way to keep making progress when travis is failing.

Follow up PR to see whether we can fix travis is at #5104

**Pull request merged**
