### PR TITLE
SISRP-5147 and SISRP-5148 - T&C and Title4 POST endpoints

### PR DESCRIPTION
**Pull request by ctweney**
Addresses https://jira.berkeley.edu/browse/SISRP-5147 and https://jira.berkeley.edu/browse/SISRP-5148 .

The front end does not yet call these endpoints. Here's how to do that: 
POST /api/campus_solutions/terms_and_conditions?uc_response=Y&aid_year=2016
POST /api/campus_solutions/title4?uc_response=N

Or put params in the form body and Rails will figure it out. 

Both T&C and Title4 go thru the hub. Params are sent to CS via the hub as an XML document. We use Rails to_xml to convert. It needs a couple of specific options because CS will choke on whitespace/newline.

### CODE REVIEW

**Comment by christianv** [comment]
@ctweney would it be possible to change it to this:

Doing a POST to: `POST /api/campus_solutions/terms_and_conditions` with the following POST params:
* "response": true
* "aidYear`: "2016"

We would need to do some conversion on the CalCentral back-end side.
And it might be good to look at the POST in the google tasks piece to see how we're sending the POSTs over from the front-end.

**Comment by ctweney** [comment]
Sure, I'll revise when I'm back later this afternoon.

**Comment by christianv** [comment]
@ctweney that would be great, thanks!

**Comment by ctweney** [comment]
@christianv I pushed some new commits that fix the test failure and give you a camelCased JSON API surface. Here is an example post: 

```
POST /api/campus_solutions/terms_and_conditions HTTP/1.1
Host: localhost:3000
Authorization: XXXXXX
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: dd85b234-0749-4865-bb67-c42c867640ac

{"response":"Y","aidYear":"2016"}
```

This is consistent with the tasks post. 

The camelCasing was not too hard, but unfortunately the value for "response" is still "Y" or "N". To handle your pure boolean, I'd have to build a value-mapping-and-transformation abstraction in addition to the fieldname-mapping I already have. I think that's a complexity too far.

**Pull request merged**
