### PR TITLE
 SISRP-42541 Update SISEDO views used by OEC

### PR DESCRIPTION
**Pull request by raydavis**
https://jira.berkeley.edu/browse/SISRP-42541

### CODE REVIEW

**Comment by raydavis** [comment]
The CLASSSECTIONALLV00_MVW change has broken some tests. Investigating...

**Comment by raydavis** [comment]
PR amended. One of my replacements should have been a deletion.

**Comment by raydavis** [comment]
Ready for review, @davidlimcheng (or whoever wants it)

**Comment by redconfetti** [comment]
LGTM @raydavis

**Pull request merged**
