### PR TITLE
SISRP-18764 - Update Textbook and Booklist to avoid instructor email overload

### PR DESCRIPTION
**Pull request by redconfetti**
https://jira.berkeley.edu/browse/SISRP-18764

### CODE REVIEW

**Comment by paulkerschen** [comment]
Code looks good, @redconfetti, but four commits seems like a lot of history. What would you think about squashing them down to one?

**Comment by redconfetti** [comment]
@paulkerschen So we prefer to keep updates singular, with a one-to-one ratio with assigned tasks, instead of separate so that the changes are easier to follow and understand?

**Comment by paulkerschen** [comment]
Yes, @redconfetti, unless it's quite a large task, or has some very sharp dividing line. In this case I think the functional intent of all changes is closely aligned enough that it makes sense to group them in one commit.

**Comment by redconfetti** [comment]
@paulkerschen Your zucchini is ready (green + squash)

**Comment by paulkerschen** [comment]
Yum!

**Pull request merged**
