### PR TITLE
SISRP-39478 - Student and Advisor view needs to display Academic status

### PR DESCRIPTION
**Pull request by nkutub**
https://jira.berkeley.edu/browse/SISRP-39478
* bug fixes

### CODE REVIEW

**Comment by redconfetti** [comment]
@nkutub - There's a failure in TravisCI
```
Failures:

  1) MyBadges urls: see if mungled urls from google_calendar badges != passed through urls for berkeley.edu tokens
     [31mFailure/Error: [0m@headless = [1;34;4mHeadless[0m.new([35mdisplay[0m: [1;34m98[0m)[0m
     [31m[0m
     [31mHeadless::Exception:[0m
     [31m  Xvfb is frozen[0m
     [36m# ./spec/features/google_badges_url_spec.rb:25:in `block in (root)'[0m
     [36m# /home/travis/.rvm/gems/jruby-9.1.14.0/gems/bundler-1.16.2/lib/bundler/cli/exec.rb:1:in `(root)'[0m
     [36m# /home/travis/.rvm/gems/jruby-9.1.14.0/gems/bundler-1.16.2/lib/bundler/cli/exec.rb:74:in `kernel_load'[0m
     [36m# /home/travis/.rvm/gems/jruby-9.1.14.0/gems/bundler-1.16.2/lib/bundler/cli/exec.rb:28:in `run'[0m
     [36m# /home/travis/.rvm/gems/jruby-9.1.14.0/gems/bundler-1.16.2/lib/bundler/cli.rb:424:in `exec'[0m
     [36m# /home/travis/.rvm/gems/jruby-9.1.14.0/gems/bundler-1.16.2/lib/bundler/cli.rb:27:in `dispatch'[0m
     [36m# /home/travis/.rvm/gems/jruby-9.1.14.0/gems/bundler-1.16.2/lib/bundler/cli.rb:18:in `start'[0m
     [36m# /home/travis/.rvm/gems/jruby-9.1.14.0/gems/bundler-1.16.2/exe/bundle:30:in `<main>'[0m
     [36m# /home/travis/.rvm/gems/jruby-9.1.14.0/gems/bundler-1.16.2/lib/bundler/friendly_errors.rb:124:in `<eval>'[0m
     [36m# /home/travis/.rvm/gems/jruby-9.1.14.0/gems/bundler-1.16.2/exe/bundle:22:in `<main>'[0m
```

**Comment by lyttam** [comment]
@nkutub For some reason Github won't let me add a comment on the file.  This line appears to be missing a single quote after GST:

`<tr data-ng-if="semester.hasStandingData && semester.standing.acadStandingStatus !== 'GST">`

Also, what does GST mean?

**Comment by nkutub** [comment]
@lyttam , fixed, 'GST' is code for good standing.

**Comment by lyttam** [comment]
@nkutub Thanks. In the future we should add a flag to the object or write a function, e.g. `isInGoodStanding`, to make this clear.

**Pull request merged**
