### PR TITLE
NOJIRA - rename faculty-resources.html to faculty_resources.html

### PR DESCRIPTION
**Pull request by dfkaye**

### CODE REVIEW

**Comment by johncrossman** [comment]
@dfkaye Does this really need a Jira?  I would prefix the summary with 'NOJIRA' and ask for a merge.

**Comment by redconfetti** [comment]
Or I would perhaps at least add it as a line item to some task that it's related to somehow in the next sprint.

**Comment by dfkaye** [comment]
thanks @johncrossman - I've updated per the NOJIRA suggestion

**Comment by johncrossman** [comment]
Thanks @dfkaye

**Pull request merged**
