### PR TITLE
SISRP-5399 - Front End Dev: Profile Tab - Basic Information Card

### PR DESCRIPTION
**Pull request by christianv**
https://jira.berkeley.edu/browse/SISRP-5399

### CODE REVIEW

**Comment by ctweney** [comment]
@christianv I can't tell if that Travis failure is legit or not. It looks like the JSHint problem that @paulkerschen and @johncrossman encountered this morning.

**Comment by ctweney** [comment]
LGTM apart from Travis failure.

**Comment by christianv** [comment]
@ctweney let's try to merge #4165 first and then I'll re-push this branch

**Comment by christianv** [comment]
Restarted the build

**Pull request merged**
