### PR TITLE
CLC-5003 Remove large size for GPA

### PR DESCRIPTION
**Pull request by szhu**
Most students visit the Academics tab to check things other than GPA, so there's no particular reason for GPA to be larger.

In addition, many students visit CalCentral in public settings and would prefer to have their GPA less visible to people around them.

This is a temporary solution, but a "show GPA" checkbox might be more appropriate in the future.

Before:
screen shot 2015-03-18 at 1 56 34 am

After:
screen shot 2015-03-18 at 1 56 42 am

### CODE REVIEW

**Comment by raydavis** [comment]
Makes sense, @szhu, but usually we'd want a JIRA ticket for changes to the design. Could we get a weigh-in from Flint here or in JIRA?

**Comment by flint-hahn** [comment]
@szhu - I too have heard comments from students who would prefer to deemphasize the GPA information. Attached is the suggested updated.
screen shot 2015-03-18 at 9 16 26 am

**Comment by raydavis** [comment]
Thanks, @flint-hahn -- I created a ticket for easier tracking (except for @szhu , I guess!) at: https://jira.ets.berkeley.edu/jira/browse/CLC-5003

**Comment by raydavis** [comment]
@szhu , would you be able to adjust your PR to better match @flint-hahn 's design? Looks like it's just a matter of enlarging the name size and moving the de-emphasized GPA down a bit.

**Comment by szhu** [comment]
a344e85b1d486493d874df5416d4f3cdbbb0b276 should do this! Preview:

screen shot 2015-03-20 at 2 29 00 am

**Comment by raydavis** [comment]
Thank you for reporting AND fixing this, @szhu -- looks great! Unfortunately, there's still one small step left to take. The automated Travis CI code check failed on a CSS style point. If you click on "Details" in the "Failed" message on this page, you'll see:

```
src/assets/stylesheets/_profile.scss:13 [W] ZeroUnit: `0px` should be written without units as `0`
scss-lint failed
```

Nitpicky or not, all us devs are slaves to Travis. Would you mind adding one more commit to remove those two letters? Then we can finally merge.

**Comment by szhu** [comment]
Oh, I forgot to follow up on checking the build status, awkward. Fixed by 3e165416f218d9f2eec6252259f3245a33f26626.

**Comment by szhu** [comment]
So the build failed (I think rubygems was down for a bit) and in trying to get it to rebuild I accidentally closed this PR. Can someone reopen it (and rerun the build for 3e165416f218d9f2eec6252259f3245a33f26626)?

**Pull request closed without merging**
