### PR TITLE
SISRP-34657 - Marks faculty committee as active based on service date

### PR DESCRIPTION
**Pull request by lyttam**
https://jira.berkeley.edu/browse/SISRP-34657

Previously, a committee was presented to faculty as 'Completed' if the student had finished the necessary milestones.  With this change we will instead show a faculty committee as 'Completed' if the faculty member's service on the committee has ended.

### CODE REVIEW

**Comment by davidlimcheng** [comment]
Travis errored out in the bundler step, I'm going to restart it to see if that was just a hiccup.

**Comment by lyttam** [comment]
`bundle install` is failing. Somehow we're back to using bundler v1.15.4, which won't work with our Gemfile.lock.

**Comment by lyttam** [comment]
Actually, it's not the bundler version that changed - it's the RubyGems version.

Successful build:
```$ bundle --version
Bundler version 1.15.4
$ gem --version
2.4.5
```$ bundle --version
Bundler version 1.15.4
$ gem --version
2.6.13```

**Comment by raydavis** [comment]
@lyttam , yep. If I'm reading the docs right, adding this to `.travis.yml` might fix our sad little PRs:

```
before_install:
  - gem update --system 2.4.5
```

**Comment by lyttam** [comment]
@raydavis Yeah, I tried running `gem update --system 2.4.5` locally before running `bundle install` with bundler v1.15.2 and it worked.

I supposed we'll have to get to the root of the problem eventually though.  I ran `bundle update` with `--verbose` and it looks like RubyGems can't find or parse the .gemspec file in jruby-activemq.

**Comment by lyttam** [comment]
I pulled in Ray's fix to .travis.yml and the build succeeded.  This is ready to merge.  I will keep looking for a long-term solution to the problem.

**Pull request merged**
