### PR TITLE
CLC-6415, gem update selenium-webdriver: 2.46.2 --> 2.53.4

### PR DESCRIPTION
**Pull request by johncrossman**
https://jira.ets.berkeley.edu/jira/browse/CLC-6415

The goal is to repair https://jira.ets.berkeley.edu/jira/browse/CLC-6413

### CODE REVIEW

**Comment by johncrossman** [comment]
Example of Bamboo breakage due to selenium wonkiness: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CLCMVPMASTER-4415

**Comment by johncrossman** [comment]
Do not merge until my personal Bamboo build is happy:
https://bamboo.ets.berkeley.edu/bamboo/browse/CPB-CJT82-1

**Comment by raydavis** [comment]
Thanks, @johncrossman -- watching with interest...

**Comment by johncrossman** [comment]
@raydavis build failed on CampusSolutions and Hub specs. I quarantined and kicked off a retry: https://bamboo.ets.berkeley.edu/bamboo/browse/CPB-CJT82-2

**Pull request merged**
