### PR TITLE
SISRP-13602 - UX DESIGN: Lack of Visual Arrow Indicator on Activity Card in Billing Details Page

### PR DESCRIPTION
**Pull request by nkutub**
This PR is finishing off the PR https://github.com/ets-berkeley-edu/calcentral/pull/5803/commits/c53b7768ed92aa4c7ffd1b29de102b00cb9581be done by David K. if this PR is successfully merged, David's PR should be canceled.

### CODE REVIEW

**Comment by davidlimcheng** [comment]
Good stuff @nkutub!  Looks like Travis is failing due to some SCSS linting errors in `_widgets.scss`:
```
[36msrc/assets/stylesheets/_widgets.scss[0m:[35m197[0m:[35m1[0m [33m[W][0m [32mSpaceBeforeBrace: [0mOpening curly brace `{` should be preceded by one space
[36msrc/assets/stylesheets/_widgets.scss[0m:[35m219[0m:[35m3[0m [33m[W][0m [32mPlaceholderInExtend: [0mPrefer using placeholder selectors (e.g. %some-placeholder) with @extend
[36msrc/assets/stylesheets/_widgets.scss[0m:[35m237[0m:[35m3[0m [33m[W][0m [32mPlaceholderInExtend: [0mPrefer using placeholder selectors (e.g. %some-placeholder) with @extend

[ERROR] scss-lint returned non-zero status: 1
```

**Comment by nkutub** [comment]
ya was using rubymie should have used my csslint enabled editor new commit on its way.

**Comment by nkutub** [comment]
I guess I fat fingered an additional space in an unrelated holdsFactory.js file. new commit on its way

**Comment by davidlimcheng** [comment]
Awesome.   This LGTM @nkutub, but I will wait on @redconfetti's review before merging since he had a lot of comments on the previous iteration of this PR.

**Comment by raydavis** [comment]
Since @redconfetti has been out of commission for the last two days, I'll merge this now and he can add any comments later. Thanks, @davidlimcheng & @nkutub !

**Pull request merged**
