### PR TITLE
SISRP-13573, master into sis-master (act_as_controller.rb conflict?)

### PR DESCRIPTION
**Pull request by johncrossman**
https://jira.berkeley.edu/browse/SISRP-13573

Conflict resolved.

### CODE REVIEW

**Comment by johncrossman** [comment]
Okay, Travis happy. Thanks for coaching me through the merge, @raydavis

**Comment by christianvuerings** [comment]
@johncrossman thanks, but I think @raydavis or @paulkerschen are a more qualified to hit the merge button in this case.

**Comment by johncrossman** [comment]
Good catch, @raydavis  Fear not, I will figure out this damn merge.

**Comment by raydavis** [comment]
And I will most damnably merge it!

**Pull request merged**
