### PR TITLE
CLC-7059: Fixes typo in query

### PR DESCRIPTION
**Pull request by lyttam**
https://jira.ets.berkeley.edu/jira/browse/CLC-7059

### CODE REVIEW

**Comment by lyttam** [comment]
Travis builds are failing due to 404 responses when trying to download RVM.

**Comment by raydavis** [comment]
Looks like the Travis issues are frequent but not omnipresent. I restarted the master-PR Travis check and it's humming along OK; I restarted this PR's Travis check and it failed again on RVM download.

**Comment by johncrossman** [comment]
@raydavis I had reviewed (and approved) and was waiting for Travis. Thank you for taking care of business.

**Comment by raydavis** [comment]
It was @notme !!

**Pull request merged**
