### PR TITLE
SISRP-36436 - Residency data is not loading in calcentral

### PR DESCRIPTION
**Pull request by nkutub**
https://jira.berkeley.edu/browse/SISRP-36436

* remove unused spinner.

### CODE REVIEW

**Comment by lyttam** [comment]
@nkutub Looks like there's some leftovers in `academicStatusHoldsBlockController.js`, can you remove `isLoading` from here too?

```
  // Request-and-parse sequence on the student feed for California Residency status.
  angular.extend($scope, {
    residency: {
      isLoading: true,
      message: {}
    }
  });
```

**Comment by nkutub** [comment]
@lyttam , good catch

**Comment by lyttam** [comment]
@nkutub just remove ` isLoading: true,` from the controller

**Comment by davidlimcheng** [comment]
One failed rspec for a model totally unrelated to this PR (Committees).  Going to restart the tests.

**Comment by davidlimcheng** [comment]
Looking good now!

**Pull request merged**
