### PR TITLE
_profile: Remove excess whitespace above GPA

### PR DESCRIPTION
**Pull request by mc10**
I believe this (subjectively) looks better than an awkward space present.

### CODE REVIEW

**Comment by johncrossman** [comment]
@mc10  It seems we reference this in src/assets/templates/academics_student_profile.html. Shall we remove the reference or, alternatively, tweak the css to remove whitespace?

**Comment by raydavis** [comment]
I'd like a JIRA ticket on this, preferably with a screenshot, before merging. @mc10, do you have access to our ticketing system? If not, @johncrossman or I can take care of that.

**Comment by raydavis** [comment]
Ah, now I see @mc10 's open issue: https://github.com/ets-berkeley-edu/calcentral/issues/3888

**Comment by raydavis** [comment]
JIRAfied: https://jira.ets.berkeley.edu/jira/browse/CLC-5421

**Comment by mc10** [comment]
@raydavis That's a separate styling issue, one that I don't have a solution for. Should I create another issue for this PR?

**Comment by paulkerschen** [comment]
@mc10 Yes, feel free to create another issue for this PR. #3888 duplicates #3882 and the fix went live this morning. Thank you!

**Comment by paulkerschen** [comment]
JIRA for this PR: https://jira.ets.berkeley.edu/jira/browse/CLC-5422

**Comment by mc10** [comment]
Alright, created issue #3891.

**Comment by raydavis** [comment]
@mc10, thank you for this and the other PRs / issues you've taken time to volunteer to us. (And apologies for the overhead of our process.)

I think the discussion at https://github.com/ets-berkeley-edu/calcentral/issues/3891 is proving fruitful, but I also think the team is in agreement that this particular code change diverges too much from the existing design and that we should address the problem you've found in some other way. I'm therefore going to close this particular PR for now. As you can see from our past PR history, all of us on the team have had to close our first attempts at fixes at some point or another, and so please do not feel discouraged -- we welcome the help!

**Comment by mc10** [comment]
That's fine, thanks for the suggestions!

**Pull request closed without merging**
