### PR TITLE
CLC-5620 Really honestly fix Bamboo failures

### PR DESCRIPTION
**Pull request by paulkerschen**
Please do not merge until Bamboo checks out: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CPT139-14

### CODE REVIEW

**Comment by johncrossman** [comment]
Bamboo is no happy. It seems that course_code_spec sets up test data which duplicates seed-data.

**Comment by paulkerschen** [comment]
@johncrossman Indeed. I've pushed a workaround and Bamboo will try here: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CPT139-15

But we certainly have too much duplication between seed, migration and test data, and at some point it would be good to work out a better pattern for consistent database population across environments.

**Comment by johncrossman** [comment]
I agree @paulkerschen With less test data mayhem, I wouldn't wince at schema changes. A good topic for sprint retrospective.

**Comment by paulkerschen** [comment]
@johncrossman Looks like that last amendment finally unclogged the pipes.

**Comment by johncrossman** [comment]
All clear on the Bamboo front.

**Pull request merged**
