### PR TITLE
[QA] SISRP-26305 - MyAcademics::Exams for UID 1064465: NoMethodError: undefined method gsub for nil:NilClass

### PR DESCRIPTION
**Pull request by davidlimcheng**
QA PR of #5930.

### CODE REVIEW

**Comment by johncrossman** [comment]
@davidlimcheng I believe #5928 must be merged in order to get a happy Travis.

**Comment by davidlimcheng** [comment]
@johncrossman Gotcha, I'll force push once again after #5928 has been merged.

**Comment by davidlimcheng** [comment]
@johncrossman , should be good to go.

**Comment by johncrossman** [comment]
Thanks @davidlimcheng

**Pull request merged**
