### PR TITLE
SISRP-25535 / SISRP-25533 - Removes line separator and adds tentative message

### PR DESCRIPTION
**Pull request by tiffanyqi**
https://jira.berkeley.edu/browse/SISRP-25533
https://jira.berkeley.edu/browse/SISRP-25535

Two very small bugs that are now fixed that:
1) Show the message that final exams are tentative
2) Removes the line if there is only one semester present

### CODE REVIEW

**Comment by raydavis** [comment]
Hey, @tiffanyqi , these changes look fine. But in the vast territory of your earlier PR, I missed the new "curr" property being slipped into the My Academics "semesters" feed. 

``"curr": true`` seems to mean exactly the same thing as ``"time_bucket": "current"``. For example, ``!semester.curr`` can be replaced by ``(semester[:timeBucket] !== 'current')``.

It would be better to work directly with ``time_bucket`` than to add more bulk to the feed and to make your exams JS code use different logic than the other JS code in Academics. Would you be OK with changing that bit in a follow-up PR?

**Comment by tiffanyqi** [comment]
@raydavis sure, I'll change that real quick. Should I preface the commit with 'NOJIRA'?

**Comment by raydavis** [comment]
If it was me, since it's all aimed at the same release, I'd just re-use the JIRA number used for the initial PR and note the follow-up in JIRA. (I have to do after-thought changes a lot!)

**Comment by tiffanyqi** [comment]
@raydavis added! https://github.com/ets-berkeley-edu/calcentral/pull/5869

Thanks!

**Pull request merged**
