### PR TITLE
SISRP-41516 - Delegates - Financial Resource Card Endless Spinning Bug

### PR DESCRIPTION
**Pull request by davidlimcheng**
https://jira.berkeley.edu/browse/SISRP-41516

### CODE REVIEW

**Comment by davidlimcheng** [comment]
Thanks @lyttam, title changed, but please hold off on merging as something just popped up in the JIRA.

**Comment by davidlimcheng** [comment]
OK fixed the issue @lyttam, I had to actually remove delegate access to `FinancialResources`. Should be good to go upon re-review.

**Comment by davidlimcheng** [comment]
Ahh scratch that.  One more requirement change, sorry.

**Comment by davidlimcheng** [comment]
OK, really good to go now, @lyttam.  Made it so that delegates won't trigger any API calls that don't need to be made on the front-end, and removed the delegate access I previously gave to those links.

**Comment by lyttam** [comment]
Looks great.

**Pull request merged**
