### PR TITLE
SISRP-19389 - Remove 'Schedule Planner' link from Advising Resources Widget

### PR DESCRIPTION
**Pull request by redconfetti**
https://jira.berkeley.edu/browse/SISRP-19389

### CODE REVIEW

**Comment by redconfetti** [comment]
Hold off on merging this. The link can be on the homepage, but without the EMPLID included.

**Comment by johncrossman** [comment]
@redconfetti Is it also being removed from the CS API? If so, remove it from fixture `college_scheduler_url.xml`, too

**Comment by redconfetti** [comment]
@johncrossman No. It will still be featured on the 'Personal Summary' card, but will point to CS with an EMPLID included in the query string. Given that in a future release it will come from the API, I believe that we should leave it in the XML fixture for now.

See [Jira Comment](https://jira.berkeley.edu/browse/SISRP-19386?focusedCommentId=362489&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-362489) for more details

**Comment by johncrossman** [comment]
Thanks @redconfetti  Looks good

**Comment by johncrossman** [comment]
@redconfetti Is this expected in Sunday's v76.1 release?

**Comment by redconfetti** [comment]
@johncrossman Yes. It is expected in GL 5.4b. I believe this is CLC v76.1, but I would need someone to confirm this.

**Pull request merged**
