### PR TITLE
OEC-561, diff task: log proper message when no diff found

### PR DESCRIPTION
**Pull request by johncrossman**
https://jira.ets.berkeley.edu/jira/browse/OEC-561

Includes:
1. log level tweaks
2. def diff_found? on CoursesDiff
3. mo' better messaging in oec.rake

### CODE REVIEW

**Comment by paulkerschen** [comment]
Not picking a nit so much as pure curiosity, @johncrossman : why the `diff_found?` method instead of setting `attr_reader` on `@difference_found`? Is it just to have the question mark make clear it's a boolean?

**Comment by johncrossman** [comment]
@paulkerschen Thanks. I'll use attr_reader and add test in spec.

**Comment by johncrossman** [comment]
@paulkerschen  Change is in. To answer your question, using method (instead of attr_reader) gave readability (ie, '?') and default boolean (nil is false). Readability now comes with new var name. Default is explicitly set in init. I thought of using alias_method (with attr_reader) to get '?' in method but that's over-engineering.

**Comment by paulkerschen** [comment]
Makes sense to me! Half a Travis.

**Pull request merged**
