### PR TITLE
SISRP-22695 CalDap user attributes should not depend on legacy SIS data

### PR DESCRIPTION
**Pull request by raydavis**
https://jira.berkeley.edu/browse/SISRP-22695

There's a lot more legacy-code cleanup to do, but this bit is urgent. If it's not eliminated, then I believe Oracle user attributes will start throwing nil exceptions at the end of the Summer term.

### CODE REVIEW

**Comment by raydavis** [comment]
Pinging @davidlimcheng , @redconfetti for review.

**Comment by davidlimcheng** [comment]
LGTM @raydavis - awaiting review from @redconfetti.

**Comment by raydavis** [comment]
I'm not sure @redconfetti will have time -- anyone else want a crack at it?

**Comment by paulkerschen** [comment]
+24 −396 is the winning diff count for the month. Thanks @raydavis.

**Pull request merged**
