### PR TITLE
SISRP-9937 - CalCentral API: Sending over a null to the back-end for address POST converts it into bad XML for CS

### PR DESCRIPTION
**Pull request by christianv**
https://jira.berkeley.edu/browse/SISRP-9937

### CODE REVIEW

**Comment by christianv** [comment]
Also reverts #4416

**Comment by ctweney** [comment]
@christianv Actually I think I'd like to keep the change from #4416 -- it's a defense against accidental nulls sent from the front-end -- but also have the front-end do its value-or-blank logic in this particular case.

**Comment by christianv** [comment]
@ctweney K, I'll follow up

**Comment by christianv** [comment]
@ctweney see follow up, just changed the front-end code.

**Comment by ctweney** [comment]
Looks great, thanks for the change!

**Pull request merged**
