### PR TITLE
SISRP-12376 - Remove the 'Do Not Display' code from CalCentral

### PR DESCRIPTION
**Pull request by davidlimcheng**
https://jira.berkeley.edu/browse/SISRP-12376

### CODE REVIEW

**Comment by davidlimcheng** [comment]
@christianvuerings - For the 'def redact_sensitive_keys' definition in student.rb, is this something I should leave in case it's used in the future for any reason?  If not, I can go ahead and push a new commit up after deleting it.

**Comment by christianvuerings** [comment]
@davidlimcheng since we don't use `redact_sensitive_keys` anywhere anymore, I would definitely suggest removing it as part of this PR.

Also have a look at the Travis CI failure.

**Comment by davidlimcheng** [comment]
@christianvuerings Sounds good, I'll delete it and push a new commit.  I think the Travis was another false negative since there are no logs, I'll try to rerun it and see what comes up.

**Comment by davidlimcheng** [comment]
Drats failed again.  I'll take a deeper look at it.

**Comment by paulkerschen** [comment]
@davidlimcheng It looks like all the "missing template" failures on Travis are a red herring - they only appear in one of the two build. The test failure that appears in both builds is the following:

```
HubEdos::Contacts mock proxy returns data with the expected structure
     Failure/Error: expect(subject[:feed]['student']['addresses'][0]['postal']).to eq '94720'
       
       expected: "94720"
            got: "94708"
       
       (compared using ==)
     # ./spec/models/hub_edos/contacts_spec.rb:14:in `(root)'
```

**Comment by paulkerschen** [comment]
@davidlimcheng The solution might be to edit `fixtures/json/student_contacts.json` to remove the "Do Not Display" code, same as you did with `fixtures/json/student_api_via_hub.json`.

**Comment by davidlimcheng** [comment]
@paulkerschen Thank you!  I'll give it a shot.  I presume I'll also have to update the consistency check in `contacts_spec.rb`, i.e. 

```ruby
expect(subject[:feed]['student']['addresses'][0]['postal']).to eq '94720'
```

Should be eq to 94708.

**Comment by davidlimcheng** [comment]
Along with `formattedAddress`

**Comment by davidlimcheng** [comment]
@christianvuerings @paulkerschen Hurrah!

**Comment by christianvuerings** [comment]
lgtm - @pfarestveit definitely something we should check during QA - setting an address / name / phone / ... to `Do Not Display` in CS and seeing whether it shows up in CalCentral.

**Pull request merged**
