### PR TITLE
SISRP-19059 Hub caching fixes; support filtering of cached feeds at the model layer

### PR DESCRIPTION
**Pull request by raydavis**
https://jira.berkeley.edu/browse/SISRP-19059

Further on this long march, again clustered by commit. If you're wondering where this is going, planned next steps are:

- ~~Centralize Residency logic in a new feed, stripping Demographics to the actual Hub data.~~ (Included in latest commit.)
- Reduce Hub dependencies in UserAttributes.
- Extract hasPhoto from User::Api.
- Given a slimmer User::Api cost, switch classes which pull from uncached subsets of user attributes over to the extremely cached User::Api feed.

### CODE REVIEW

**Comment by raydavis** [comment]
@redconfetti , @davidlimcheng , @nkutub, @tiffanyqi , @dfkaye , & potentially @paulkerschen - Code review will probably be easiest if you look at one commit at time.

**Comment by paulkerschen** [comment]
Thanks for this much-needed cleanup, @raydavis. I've gone through it all and it looks right and good to me, but perhaps I'll leave it up a bit longer in case any of the others above named want a look?

**Comment by paulkerschen** [comment]
Going, going, merged.

**Comment by raydavis** [comment]
Thanks, @paulkerschen ! As you seem to have noticed, the two most likely SIS reviewers are both unavailable today, but I'm definitely interested in any post-merge comments!

**Pull request merged**
