### PR TITLE
SISRP 17880 - Repackage Compare Card - Show difference with icons / gaps

### PR DESCRIPTION
**Pull request by mDibyo**
https://jira.berkeley.edu/browse/SISRP-17880

### CODE REVIEW

**Comment by raydavis** [comment]
Thank you, @mDibyo . This looks good to me, but I'd like @davidlimcheng to take a look too if he has time.

One request, though. Would you mind squashing these 12 commits down into just one? That will make it easier to cherry-pick, revert, etc., and easier to understand the commit log history. Thanks!

**Comment by mDibyo** [comment]
@raydavis That makes sense. Done!

**Comment by raydavis** [comment]
Thanks for the squash, @mDibyo . Since we're short on other reviewers today, I'll go ahead and merge now.

**Comment by mDibyo** [comment]
@raydavis Thanks!

**Pull request merged**
