### PR TITLE
SISRP-14635 - Enrollment card: front end for academic planner deeplink

### PR DESCRIPTION
**Pull request by christianvuerings**
https://jira.berkeley.edu/browse/SISRP-14635

Also fixes:

SISRP-14634 - Class Scheduler outbound link should open in new window

https://jira.berkeley.edu/browse/SISRP-14634

### CODE REVIEW

**Comment by christianvuerings** [comment]
Didn't verify the back-end tests yet - so travis might turn red.

**Comment by christianvuerings** [comment]
Let's hold off for a minute - making a couple of more changes to this card since now we have some `real` data.

**Comment by christianvuerings** [comment]
Also updated a bunch of links - we should be good for a review now.

**Comment by paulkerschen** [comment]
@christianvuerings Looks like the Decal link at least should be removed from the back-end spec to make Travis happy.

**Comment by christianvuerings** [comment]
@paulkerschen thanks - just updated the spec

**Comment by paulkerschen** [comment]
Thanks @christianvuerings - looks good.

**Pull request merged**
