### PR TITLE
SISRP-11283 - GL3 Remove hardcoded SIR response messages

### PR DESCRIPTION
**Pull request by christianvuerings**
https://jira.berkeley.edu/browse/SISRP-11283

### CODE REVIEW

**Comment by paulkerschen** [comment]
@christianvuerings With this change, it looks like the contents of the two div.cc-widget-text elements are identical. Would it be better to combine the data-ng-if conditions for these two; or is that condition perhaps no longer needed?

**Comment by christianvuerings** [comment]
@paulkerschen thank you! Really good point, I'll make it update.

**Comment by christianvuerings** [comment]
@paulkerschen pushed the update

**Comment by paulkerschen** [comment]
LGTM @christianvuerings, waiting for T.

**Pull request merged**
