### PR TITLE
CLC-5805 - Add Show / Hide GPA functionality

### PR DESCRIPTION
**Pull request by christianv**
https://jira.ets.berkeley.edu/jira/browse/CLC-5805

### CODE REVIEW

**Comment by christianv** [comment]
We need to make sure @raydavis has a chance to look at this before merging.

**Comment by raydavis** [comment]
Travis is half-full.

**Comment by raydavis** [comment]
Works for me, @christianv -- thank you for the ping.

OK if we wait a bit on the merge to clear the decks for our emergency release? Should only be an hour.

**Comment by christianv** [comment]
@raydavis Thank you and yes, waiting a bit is totally fine.

**Pull request merged**
