### PR TITLE
SISRP-22098: remove textbook references for law

### PR DESCRIPTION
**Pull request by tiffanyqi**
https://jira.berkeley.edu/browse/SISRP-22098

A simple fix in which I change the error message especially for law in the template. Wasn't sure how to do it in the errorMessage itself, so I put a fix here.

### CODE REVIEW

**Comment by raydavis** [comment]
The JIRA ticket seemed ambiguous on this, @tiffanyqi , so I left a comment asking whether the deciding factor was what school the _class_ is in rather than what school(s) the student or teacher/GSI was in.

**Comment by raydavis** [comment]
Would the studentInfo property pick up teaching staff? (I ask because the JIRA ticket specifically calls out "law faculty".)

**Comment by tiffanyqi** [comment]
@raydavis that's a really good point. It should probably be whether the class is law.

**Comment by raydavis** [comment]
@tiffanyqi , I'm going to close this for now so as not to distract PR reviewers during QA. Look forward to the new version!

**Pull request closed without merging**
