### PR TITLE
SISRP-17104 Fixes to User::Api caching

### PR DESCRIPTION
**Pull request by raydavis**
First installment of https://jira.berkeley.edu/browse/SISRP-17104 .

NOTE: The commit messages are longer than the code changes. I expect that pattern to continue!

### CODE REVIEW

**Comment by johncrossman** [comment]
I look forward to these simplifications, @raydavis  I'll merge once Travis failure gets a little love.

**Comment by raydavis** [comment]
Ouch. Given the number of test failures resulting from these three deleted lines, I'm going to have to increase my time estimate for the task.

**Comment by raydavis** [comment]
Not actually so bad -- I missed one critical line change.

**Comment by raydavis** [comment]
Travis's demands were reasonable and have been met.

**Comment by johncrossman** [comment]
Travis greenery abounds. Thx @raydavis

**Pull request merged**
