### PR TITLE
SISRP-1844 - Connect Slate checklist feed to My ToDo

### PR DESCRIPTION
**Pull request by ctweney**
https://jira.berkeley.edu/browse/SISRP-1844

Fake feed from Slate, but the real one works as well if you have the right credentials. This still needs a UI icon to represent Slate tasks. 

@christianv should review.

### CODE REVIEW

**Comment by christianv** [comment]
lgtm - feel free to self merge when travis is green. As for the slate icon, that should have been added in https://github.com/ets-berkeley-edu/calcentral/commit/9b0b866dfecefc9fd2d561e9cf8bb3939762047d

**Comment by ctweney** [comment]
I pushed a new commit that fixes the mock feed to match what's coming out of Slate now (last-minute update). 

My mistake on the Slate task icon: It is there, I had just forgotten to gulp build after merging in your changes.

**Comment by christianv** [comment]
New changes lgtm

**Comment by ctweney** [comment]
Self-merging so this can get onto sis-dev sooner.

**Pull request merged**
