### PR TITLE
CLC-5589 New ActiveRecord model for service alerts

### PR DESCRIPTION
**Pull request by paulkerschen**
https://jira.ets.berkeley.edu/jira/browse/CLC-5589

Note that the `preview` method plus rails_admin configuration should allow alerts to be created, previewed and published right from within ccadmin.

### CODE REVIEW

**Comment by paulkerschen** [comment]
Bamboo https://bamboo.ets.berkeley.edu/bamboo/browse/CPB-CPT237-5/

**Comment by raydavis** [comment]
Thank you for taking on this important but much deferred task, @paulkerschen . This looks like a great start. Two starting questions:

* Our current UX shows the "title" as a banner alert and at the top of the front-page display and the "body" will show up on the alert display page and (HTML-sanitized) in the front-page display. But where will the required "summary" field be used?

* What would you think about adding a defaulted-but-editable "publication_date" field (to be prefixed to the title in display)? The Drupal version has occasionally been handy when preparing a service alert in advance.

**Comment by paulkerschen** [comment]
@raydavis: "publication_date" is a good idea; I'll amend to add it.

"Summary" is intended to be used as "snippet" is used in the front-page display on the current UX:

https://github.com/ets-berkeley-edu/calcentral/blob/master/src/assets/templates/splash.html#L22

My understanding was that the snippet text displayed on the front page doesn't necessarily include the entire contents of the alert body.

**Comment by raydavis** [comment]
I believe that was the original idea, @paulkerschen , but in practice it almost always turns out just to be the body of the alert. If we do decide to keep that flexibility (for when the body text only makes sense with full HTML formatting, for example), we'll want the "summary" to be either not-required or filled in automatically. How about making it not-required?

**Comment by paulkerschen** [comment]
Makes sense to me, @raydavis!

**Comment by paulkerschen** [comment]
Thanks for the feedback, @raydavis. PR amended with changes:
- Snippet field made optional;
- Defaulted-but-editable publication date added;
- Feed properties made consistent with EtsBlog::RSSProxy for easier merge into existing structures. Includes a `link` property pointing to the to-be-implemented `/alert` path.

**Comment by raydavis** [comment]
Lookin' sharp, @paulkerschen -- thank you again for taking this on!

**Pull request merged**
