### PR TITLE
NOJIRA - let's see whether this might be a fix for travis

### PR DESCRIPTION
**Pull request by christianvuerings**

### CODE REVIEW

**Comment by raydavis** [comment]
That hash is very promising...

**Comment by paulkerschen** [comment]
That's pretty good, though I once got `abfab` in a Git commit.

**Comment by redconfetti** [comment]
[For history](https://github.com/azer/left-pad/issues/4#issuecomment-200067613)

**Comment by raydavis** [comment]
```
npm ERR! git clone git@github.com:github:azer/left-pad Cloning into bare repository '/home/travis/.npm/_git-remotes/git-github-com-github-azer-left-pad-bc2ef79e'...
npm ERR! git clone git@github.com:github:azer/left-pad Permission denied (publickey).
npm ERR! git clone git@github.com:github:azer/left-pad fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:github:azer/left-pad 
npm ERR! git clone git@github.com:github:azer/left-pad Please make sure you have the correct access rights
npm ERR! git clone git@github.com:github:azer/left-pad and the repository exists.
npm ERR! notarget No compatible version found: left-pad@'github:azer/left-pad#bff80e3ef0db0bfaba7698606c4f623433d14355'
```

**Comment by redconfetti** [comment]
@christianvuerings, I think the issue is resolved with the original package. NPM un-un-published the package.

See [Laurie Voss post](https://twitter.com/seldo/status/712414588281552900)

I am able to `npm install` fine now in master.

**Comment by christianvuerings** [comment]
@redconfetti indeed - thanks - this was a fallback when they wouldn't have `un-un-published`

**Pull request closed without merging**
