### PR TITLE
[QA] SISRP-23268 - 6.0d - Student Forms card

### PR DESCRIPTION
**Pull request by dfkaye**
Master PR https://github.com/ets-berkeley-edu/calcentral/pull/5732

### CODE REVIEW

**Comment by raydavis** [comment]
@dfkaye, @pfarestveit : Given that this would effectively add an entirely new feature during QA week, it might be wise to postpone the QA merge until the master-branch version can be verified on a test server. Let's check with Ben & Co. at standup?

**Comment by benhubbard** [comment]
It will be pretty significant to drop this card. My understanding based on conversations last week was that this was a fairly low-risk QA-PR since it didn't impact the load testing. Let's discuss at stand-up.

**Comment by raydavis** [comment]
Sorry, @benhubbard , issues of electronic communication! I wasn't suggesting dropping the card, just doing a sanity check on one of the master-branch servers before submitting it to regular QA.

**Comment by benhubbard** [comment]
Thanks, @raydavis !

**Comment by raydavis** [comment]
Thanks, @dfkaye !

**Pull request merged**
