### PR TITLE
SISRP-10922 Remove duplicate key in CalCentral .jscrc

### PR DESCRIPTION
**Pull request by mDibyo**
https://jira.berkeley.edu/browse/SISRP-10922

### CODE REVIEW

**Comment by mDibyo** [comment]
Build is failing because of the new linting config.

Earlier, the second (duplicate) key-value pair for "requireSpaceAfterBinaryOperators" was overwriting the first one. The first value list contains comma (",") as one of the operators, while the second one does not. (check end of build log: https://api.travis-ci.org/jobs/91464591/log.txt?deansi=true)

There are two ways to resolve this: 
- we keep comma in the list, and I can go in and fix the linting errors.
- we remove comma from the list.

**Comment by christianvuerings** [comment]
@mDibyo looks like we still have an error with `jscs`, could you have another look? It's totally fine with me to actually add a space after the `,`

```
Running jscs - JavaScript Style Checker
Operator , should not stick to following expression at ./src/assets/javascripts/angular/controllers/widgets/carsController.js :
   222 |
   223 |  var statuses = {
   224 |    'open': ['Current','Past due','Future', 'Error', 'Installment', 'Open'],
-------------------------------^
   225 |    'minimumamountdue': ['Current','Past due'],
   226 |    'all': ['Current','Past due','Future', 'Closed', 'Error', 'Unapplied', 'Installment', 'Open']

Operator , should not stick to following expression at ./src/assets/javascripts/angular/controllers/widgets/carsController.js :
   222 |
   223 |  var statuses = {
   224 |    'open': ['Current','Past due','Future', 'Error', 'Installment', 'Open'],
------------------------------------------^
   225 |    'minimumamountdue': ['Current','Past due'],
   226 |    'all': ['Current','Past due','Future', 'Closed', 'Error', 'Unapplied', 'Installment', 'Open']

Operator , should not stick to following expression at ./src/assets/javascripts/angular/controllers/widgets/carsController.js :
   223 |  var statuses = {
   224 |    'open': ['Current','Past due','Future', 'Error', 'Installment', 'Open'],
   225 |    'minimumamountdue': ['Current','Past due'],
-------------------------------------------^
   226 |    'all': ['Current','Past due','Future', 'Closed', 'Error', 'Unapplied', 'Installment', 'Open']
   227 |  };

Operator , should not stick to following expression at ./src/assets/javascripts/angular/controllers/widgets/carsController.js :
   224 |    'open': ['Current','Past due','Future', 'Error', 'Installment', 'Open'],
   225 |    'minimumamountdue': ['Current','Past due'],
   226 |    'all': ['Current','Past due','Future', 'Closed', 'Error', 'Unapplied', 'Installment', 'Open']
------------------------------^
   227 |  };
   228 |

Operator , should not stick to following expression at ./src/assets/javascripts/angular/controllers/widgets/carsController.js :
   224 |    'open': ['Current','Past due','Future', 'Error', 'Installment', 'Open'],
   225 |    'minimumamountdue': ['Current','Past due'],
   226 |    'all': ['Current','Past due','Future', 'Closed', 'Error', 'Unapplied', 'Installment', 'Open']
-----------------------------------------^
   227 |  };
   228 |


5 code style errors found.
```

**Comment by mDibyo** [comment]
Haha, that's what I was referring to in my previous comment. I have fixed the linting errors.

**Comment by christianvuerings** [comment]
lgtm

**Pull request merged**
