### PR TITLE
SISRP-18222 - 3-2-1 Columns in CalCentral

### PR DESCRIPTION
**Pull request by redconfetti**
https://jira.berkeley.edu/browse/SISRP-18222

* Adds 2-column layout support to page templates
* Adjusts the My Campus widget width percentage for medium width devices (40% to 60%)
* Adds styles to support removal of right-gutter for 2nd column in 2-column layouts, as well as when medium viewport in use (which reduce to 2-column layout)
* Removes right gutter from Roster view when instructor viewing class page

### CODE REVIEW

**Comment by redconfetti** [comment]
@davidlimcheng I'm willing to go over this with you in person

**Comment by johncrossman** [comment]
@redconfetti Here's an odd request: Can you demo this change on Monday morning (10AM) prior to merge?  If the audience is happy we'll know we have a winner.

**Comment by redconfetti** [comment]
@johncrossman I'm pretty sure the 2nd Travis build isn't failing because of my CSS code.
```
Failures:

  1) Oec::PublishTask exported sheet structure data with suffixed course IDs data with suffixed course ID matching no ID without suffix it should behave like a smart suffix matcher should match appropriate data to suffixed CCN
     Failure/Error: File.read task.staging_dir.join(tmp_publish_directory, "#{filename}.csv")
     NoMethodError:
       undefined method `join' for nil:NilClass
     Shared Example Group: "a smart suffix matcher" called from ./spec/models/oec/publish_task_spec.rb:166
     # ./spec/models/oec/publish_task_spec.rb:12:in `read_exported_csv'
     # ./spec/models/oec/publish_task_spec.rb:16:in `courses'
     # ./spec/models/oec/publish_task_spec.rb:152:in `(root)'
```

**Comment by redconfetti** [comment]
@johncrossman Can we merge this now?

**Pull request merged**
