### PR TITLE
SISRP-21079 Move legacy Calendar::Queries to CampusOracle::Calendar

### PR DESCRIPTION
**Pull request by paulkerschen**
https://jira.berkeley.edu/browse/SISRP-21097

New queries will live in a parallel EdoOracle::Calendar class.

### CODE REVIEW

**Comment by redconfetti** [comment]
@paulkerschen I really like this move for the Queries class under CampusOracle. There's no place like home... there's no place......

I wonder if we should have done this with [Oec::Queries](https://github.com/ets-berkeley-edu/calcentral/blob/7f31a3d4/app/models/oec/queries.rb) as well. The OEC and Calendar query classes were those two outliers that hit databases that weren't grouped under CampusOracle.

@johncrossman What do you think?

**Comment by paulkerschen** [comment]
@redconfetti The OEC retrofit is scoped for next month, and I think that would be a great time to do a corresponding move on that queries class.

**Comment by johncrossman** [comment]
Looks good, @paulkerschen  I agree with comments above in terms of consistency. However, OEC is a standalone app and `Calendar` is a CalCentral feature. That difference might argue in favor of keeping `Oec::Queries` separate.  cc: @redconfetti

**Comment by johncrossman** [comment]
On second thought, I think it far better to move the OEC queries in the same way. The alternative might involve two directories under `/oec`: `edo_oracle` and `campus_oracle`. Shudder.

**Comment by redconfetti** [comment]
@johncrossman Yeah. I think EdoOracle::Oec or even EdoOracle::Oec::Queries would be a good way of making them associated with the DB source, but also separate for the application they serve (as they aren't shared).

**Pull request merged**
