### PR TITLE
CLC-6717 SISRP-31448 Make critical front-end prep visible in build-torquebox

### PR DESCRIPTION
**Pull request by raydavis**
https://jira.berkeley.edu/browse/SISRP-31448
https://jira.ets.berkeley.edu/jira/browse/CLC-6717

I tested this with a Bamboo build against my working branch _before_ @davidlimcheng 's latest reversions, and confirmed that the build will noisily fail if the front-end build fails:

```
build	27-Jul-2017 12:21:34	> calcentral@51.0.0 build-production /export/bamboo_data/xml-data/build-dir/CPB-CLCMVPRAY1-JOB1
build	27-Jul-2017 12:21:34	> gulp build --env production
build	27-Jul-2017 12:21:34	
build	27-Jul-2017 12:21:36	[12:21:36] Using gulpfile /export/bamboo_data/xml-data/build-dir/CPB-CLCMVPRAY1-JOB1/gulpfile.js
build	27-Jul-2017 12:21:36	[12:21:36] Starting 'build'...
build	27-Jul-2017 12:21:36	[12:21:36] Starting 'build-clean'...
...
build	27-Jul-2017 12:21:55	[12:21:55] 'build' errored after 18 s
build	27-Jul-2017 12:21:55	[12:21:55] TypeError in plugin 'run-sequence(revall)'
build	27-Jul-2017 12:21:55	Message:
build	27-Jul-2017 12:21:55	    RevAll is not a function
...
error	27-Jul-2017 12:21:55	npm ERR! calcentral@51.0.0 build-production: `gulp build --env production`
error	27-Jul-2017 12:21:55	npm ERR! Exit status 1
error	27-Jul-2017 12:21:55	npm ERR! 
error	27-Jul-2017 12:21:55	npm ERR! Failed at the calcentral@51.0.0 build-production script 'gulp build --env production'.
error	27-Jul-2017 12:21:55	npm ERR! This is most likely a problem with the calcentral package,
error	27-Jul-2017 12:21:55	npm ERR! not with npm itself.
error	27-Jul-2017 12:21:55	npm ERR! Tell the author that this fails on your system:
error	27-Jul-2017 12:21:55	npm ERR!     gulp build --env production
```

### CODE REVIEW

**Comment by davidlimcheng** [comment]
Nice, @raydavis. One question - since the `npm run build-production` command is run in `front-end-test.sh`, and none of the files generated from that is removed before running `build-torquebox.sh`, is it possible that we'll have duplicate files in the created .knob file?  Or will gulp recognize to just overwrite the existing files?

**Comment by raydavis** [comment]
When I tested it, @davidlimcheng , gulp neither duplicated nor overwrote -- it saw the stuff there & finished faster.

**Comment by davidlimcheng** [comment]
Great, in that case this LGTM.  Waiting on Travis.

**Comment by raydavis** [comment]
Some new mystery blocked this PR's last Travis tries and https://github.com/ets-berkeley-edu/calcentral/pull/6767 's last one as well. We see `travis.rake`'s "Running JSHint - detect errors and potential problems in JavaScript code" message, and then see "JSHint failed!" with no more explanation.

**Comment by redconfetti** [comment]
```
Finished in 7 minutes 8 seconds (files took 48.42 seconds to load)
3562 examples, 0 failures, 1 pending
Randomized with seed 10244
Coverage report generated for RSpec to /home/travis/build/ets-berkeley-edu/calcentral/coverage. 0 / 17183 LOC (0.0%) covered.
Running JSHint - detect errors and potential problems in JavaScript code
rake aborted!
JSHint failed!
/home/travis/build/ets-berkeley-edu/calcentral/lib/tasks/travis.rake:5:in `block in (root)'
Tasks: TOP => default => travis
(See full trace by running task with --trace)
The command "bundle exec rake" exited with 1.
cache.2
store build cache
$ bundle clean
0.02s
33.04schange detected (content changed, file is created, or file is deleted):
/home/travis/build/ets-berkeley-edu/calcentral/vendor/bundle/jruby/2.3.0/bundler/gems/ims-lti-016adac41302/.git/index
/home/travis/build/ets-berkeley-edu/calcentral/vendor/bundle/jruby/2.3.0/bundler/gems/ims-lti-016adac41302/.git/logs/HEAD
/home/travis/build/ets-berkeley-edu/calcentral/vendor/bundle/jruby/2.3.0/bundler/gems/jruby-activemq-26cf938f9d52/.git/index
/home/travis/build/ets-berkeley-edu/calcentral/vendor/bundle/jruby/2.3.0/bundler/gems/jruby-activemq-26cf938f9d52/.git/logs/HEAD
/home/travis/build/ets-berkeley-edu/calcentral/vendor/bundle/jruby/2.3.0/bundler/gems/omniauth-cas-f6704c97bd07/.git/index
/home/travis/build/ets-berkeley-edu/calcentral/vendor/bundle/jruby/2.3.0/bundler/gems/omniauth-cas-f6704c97bd07/.git/logs/HEAD
/home/travis/build/ets-berkeley-edu/calcentral/vendor/bundle/jruby/2.3.0/bundler/gems/rspec_junit_formatter-f6b272c5cd8f/.git/index
/home/travis/build/ets-berkeley-edu/calcentral/vendor/bundle/jruby/2.3.0/bundler/gems/rspec_junit_formatter-f6b272c5cd8f/.git
...
changes detected, packing new archive
.
.
.
.
uploading archive
Done. Your build exited with 1.
```

**Comment by raydavis** [comment]
Re-opening because "bundle exec rake travis" works for me, and so the only way I have of researching the Travis failure is to run Travis.

**Comment by raydavis** [comment]
To find out whether `system ("jshint .")` had genuinely failed from the jshint run, or if the failure was at a lower level (such as the `system` call itself), I modified `travis.rake` to output a version:

```
  puts "Running JSHint - detect errors and potential problems in JavaScript code"
  system ("jshint --version")
  system ("jshint .")
  raise "JSHint failed!" unless $?.exitstatus == 0
```

On my workstation, I got:

```
Running JSHint - detect errors and potential problems in JavaScript code
jshint v2.9.0
Running jscs - JavaScript Style Checker
...
```

Travis says:

```
Running JSHint - detect errors and potential problems in JavaScript code
rake aborted!
JSHint failed!
/home/travis/build/ets-berkeley-edu/calcentral/lib/tasks/travis.rake:6:in `block in (root)'
```

**Comment by raydavis** [comment]
OK, that last PR fiddle gave me enough info to decide on a sustainable way out of this mess. I'll close this PR in favor of a new JIRA ticket at https://jira.ets.berkeley.edu/jira/browse/CLC-6719 -- interested parties can follow along there.

**Pull request closed without merging**
