### PR TITLE
SISRP-12506 - Profile - work experience date info not shown if only end date exists - expected?

### PR DESCRIPTION
**Pull request by davidlimcheng**
https://jira.berkeley.edu/browse/SISRP-12506

### CODE REVIEW

**Comment by christianvuerings** [comment]
lgtm when travis shows some :green_heart:

**Comment by davidlimcheng** [comment]
Why must Travis hate me so =(

Failure looks like it has nothing to do with what I changed though, could it be a false positive?

**Comment by christianvuerings** [comment]
@davidlimcheng would recommend looking at the `details` - https://travis-ci.org/ets-berkeley-edu/calcentral/builds/108405709

image

Then you'll see 1 out of 2 is green :)

**Comment by davidlimcheng** [comment]
@christianvuerings thanks!

**Pull request merged**
