### PR TITLE
CLC-5064 Add tests for unscheduled and completed Google tasks

### PR DESCRIPTION
**Pull request by paulkerschen**
https://jira.ets.berkeley.edu/jira/browse/CLC-5064

Test coverage to follow up #3549.

### CODE REVIEW

**Comment by paulkerschen** [comment]
Closing this for now because of Bamboo issues.

**Comment by paulkerschen** [comment]
Happy Bamboo, back in action.

**Comment by raydavis** [comment]
_Everybody's_ happy.

**Comment by christianv** [comment]
@paulkerschen thanks!

**Pull request merged**
