### PR TITLE
SISRP-19036 - 5.4 Student Overview - Enrollment - Ensure Holds are pulling from Student data, not Advisor

### PR DESCRIPTION
**Pull request by davidlimcheng**
https://jira.berkeley.edu/browse/SISRP-19036

### CODE REVIEW

**Comment by davidlimcheng** [comment]
@raydavis Should this be PR'ed against QA as well?

**Comment by raydavis** [comment]
Getting late in the week, but it seems like a worthwhile fix if it tests OK. Let's check with @johncrossman & @pfarestveit ?

**Comment by johncrossman** [comment]
I'd vote yes, @davidlimcheng

**Comment by davidlimcheng** [comment]
@raydavis @johncrossman Sounds good, PR on the way

**Pull request merged**
