### PR TITLE
SISRP-13252, when CS gives bad delegate.URL we 'turn off' student's access to CS > Delegated Access

### PR DESCRIPTION
**Pull request by johncrossman**
https://jira.berkeley.edu/browse/SISRP-13252

No link is better than bad link.

### CODE REVIEW

**Comment by christianvuerings** [comment]
@johncrossman not a blocker but would it be possible to let the student know something went wrong?

**Comment by johncrossman** [comment]
@christianvuerings sure, amendment coming

**Comment by johncrossman** [comment]
PR updated @christianvuerings

**Comment by christianvuerings** [comment]
@johncrossman thanks - lgtm - holding off on merging till the GL5 Hub fix

**Pull request merged**
