### PR TITLE
CLC-6105, New defaults in config/settings.yml: cs_profile: true, cs_sir: true

### PR DESCRIPTION
**Pull request by johncrossman**
https://jira.ets.berkeley.edu/jira/browse/CLC-6105

specs can assume `cs_profile` and `cs_sir` are true. I'll update env YAMLs as needed.

### CODE REVIEW

**Comment by johncrossman** [comment]
don't merge... my `config/settings/testext.yml` slipped in

**Comment by johncrossman** [comment]
Okay, fixed `testext.yml` fixed. Ready for review.

**Comment by paulkerschen** [comment]
@johncrossman, feature flagging looks good, but what is now the relation between `spec/user/api_spec.rb` and `spec/user/api_with_campus_solutions_spec.rb`? I believe the plan was for the latter to eventually replace the former. Perhaps now is the time.

**Comment by johncrossman** [comment]
How soon is now?  Yes, I agree... I'll update.

**Comment by johncrossman** [comment]
Okay, @paulkerschen  Consolidated specs and removed api_with_campus_solutions_enabled_spec.rb

**Comment by paulkerschen** [comment]
Satisfying!

**Pull request merged**
