### PR TITLE
CLC-6021-qa - Roster photos: printing in Firefox only prints one page

### PR DESCRIPTION
**Pull request by christianvuerings**
https://jira.ets.berkeley.edu/jira/browse/CLC-6021

### CODE REVIEW

**Comment by christianvuerings** [comment]
QA PR at #4535

**Comment by johncrossman** [comment]
Looks good - thanks @christianvuerings  Our last PR before cutting the RC, methinks.

**Comment by christianvuerings** [comment]
@pfarestveit were we able to test this in DEV already?

**Comment by raydavis** [comment]
This fixes the Roster Photos LTI app. CalCentral My Academics Class Roster has a similar-yet-different bug which will require more work.

**Pull request merged**
