### PR TITLE
SISRP-22147 - 6.0d - My Campus Links - add Change of Academic Plan link

### PR DESCRIPTION
**Pull request by dfkaye**
https://jira.berkeley.edu/browse/SISRP-22147

<del>Return of the Change of Academic Plan link...</del>

Closing this - link is moving to Student Dashboard > Student Forms card - https://jira.berkeley.edu/browse/SISRP-23268

### CODE REVIEW

**Comment by davidlimcheng** [comment]
@dfkaye, I remember having some issues when trying to link to CS within `campuslinks.json`, primarily that we wouldn't have the dynamic environment switching between our test environments.  This also doesn't allow us to use our `campusSolutionsLinkDirective` which we use consistently with other links to CS (provides the CalCentral header + cache expiration).  Is there a reason why we're not using the Links API for this particular link?

**Comment by raydavis** [comment]
Redo of https://github.com/ets-berkeley-edu/calcentral/pull/5706

**Comment by dfkaye** [comment]
@raydavis We can hold off merging until I've verified the production link is ready.

**Comment by dfkaye** [comment]
@davidlimcheng - because this one goes on my campus, it's just easier to put it in json and point to production

**Pull request closed without merging**
