### PR TITLE
SISRP-22377 - 6.0d - My Academics - Academic Profile - Exp Grad Term

### PR DESCRIPTION
**Pull request by redconfetti**
https://jira.berkeley.edu/browse/SISRP-23083

* Removes cumulativeUnits data from My Academics College and Level feed (which were added in #5634)
* Retrofit CollegeAndLevel to prefer EDO Hub
* Adds Expected Graduation Term to My Academics feed for non-legacy students

### CODE REVIEW

**Comment by raydavis** [comment]
@redconfetti , you probably saw, but there are some legit-looking Travis complaints.

**Comment by redconfetti** [comment]
@raydavis Yeah. I'm checking them :)

**Comment by redconfetti** [comment]
Note: Please review but don't merge. We still need to restrict this from GRAD students

**Comment by raydavis** [comment]
Looks good from here, @redconfetti -- thank you!

**Comment by redconfetti** [comment]
Note: SISRP-23083 is mentioned in the commit messages. It's the sub-task, however this commit it actually intended for the entire parent task.

**Pull request merged**
